AllCops:
  TargetRubyVersion: 2.3

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
  - spec/**/*.rb

Style/AndOr:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

