language: ruby
rvm:
- 2.1.2
- 2.0.0
- jruby
- rbx-2
env:
  global:
  - TRAVIS=1
  # codeclimate repo token
  - secure: "hbCYInnd/+2AEj/NgjBG3OA9E5zfsfwBnKtGEhccfEoSrP1AcrFOvbfxOatIrCUJTkKqQ9a3Tglnl5N/eOIAOBIaPW14hDxhuEj524YdKKc/HqRBTkN9xwcV1qAkh2DSDcDbdcpzuoJ7s8spQ/nP1Q47j7oHe58+nHpiLTBBgjo="
