sudo: false
dist: trusty
language: ruby
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
rvm:
- 2.3
- jruby
gemfile:
- spec/gemfiles/rails_4_2.gemfile
- spec/gemfiles/rails_5_0.gemfile
- spec/gemfiles/rails_5_1.gemfile
env:
  global:
  - TRAVIS=1
  # codeclimate repo token
  - secure: "hbCYInnd/+2AEj/NgjBG3OA9E5zfsfwBnKtGEhccfEoSrP1AcrFOvbfxOatIrCUJTkKqQ9a3Tglnl5N/eOIAOBIaPW14hDxhuEj524YdKKc/HqRBTkN9xwcV1qAkh2DSDcDbdcpzuoJ7s8spQ/nP1Q47j7oHe58+nHpiLTBBgjo="
script:
- if [[ "$(rvm current)" = "ruby-"* ]]; then COVERAGE=1 fi
- bundle exec rspec --force-color --format d
- >
    if [ ! -z "$COVERAGE" ]; then
      bundle exec codeclimate-test-reporter
    fi
